// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLcu5NZJaxcNV2-8TzMSCELditGryWtAk',
    appId: '1:489198935047:web:e703fc73941ab465f69ea2',
    messagingSenderId: '489198935047',
    projectId: 'my-cloud-4a06c',
    authDomain: 'my-cloud-4a06c.firebaseapp.com',
    storageBucket: 'my-cloud-4a06c.appspot.com',
    measurementId: 'G-VXP8DWK7KX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb6N8ghf5Nr3KibmCdCGUW_HTllsd-8v0',
    appId: '1:489198935047:android:b1350c4fd4b08b11f69ea2',
    messagingSenderId: '489198935047',
    projectId: 'my-cloud-4a06c',
    storageBucket: 'my-cloud-4a06c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj-4Md055WFq8mG6ZDde1Wm7x-kZcPJ9Q',
    appId: '1:489198935047:ios:c6ea4300a750ecc1f69ea2',
    messagingSenderId: '489198935047',
    projectId: 'my-cloud-4a06c',
    storageBucket: 'my-cloud-4a06c.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );
}
